#
# Copyright (C) 2005 Jimi Xenidis <jimix@watson.ibm.com>, IBM Corporation
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA
#
# $Id$
#

LTEXT=0x100000

ISA_HEAD_OBJECTS = idt.o exceptions.o

TARGETS=	yield		\
		ipcmon

OTHER_TARGETS=	termIO		\
		henter		\
		hcow		\
		hintr		\
		busyloop	\
		fpu		\
		print		\
		check_time	\
		time_intr	\
		time_intr_yield

hintr: COMMON_OBJECTS += timer_handler.o
hintr: timer_handler.o

time_intr time_intr_yield: COMMON_OBJECTS += time_intr_common.o timer_handler.o
time_intr time_intr_yield: time_intr_common.o timer_handler.o

hcow: COMMON_OBJECTS += hcow_handler.o
hcow: hcow_handler.o

HOST_PRE_CPPDIRS += -I.

ifeq ($(ENABLE_GDB), yes)
COMMON_OBJECTS += gdb_handler.o
endif

CONTROLLER_OBJECTS += prom.o
