#!/bin/sh

# 'usb' or 'cdrom'
MODE=usb

PATH="/sbin:/bin:/usr/sbin:/usr/bin"

busybox mount -t proc proc /proc
busybox mount -t sysfs sysfs /sys

busybox --install -s

mknod /dev/null c 1 3
mknod /dev/tty c 5 0

if [ -f /etc/modules ]; then
	depmod -a
	cat /etc/modules | while read mod; do
		modprobe $mod
	done
fi

echo /bin/mdev > /proc/sys/kernel/hotplug
sleep 5
mdev -s

if [ "$MODE" = "cdrom" ]; then
	mkdir /mnt/cdrom
	mount -t iso9660 /dev/cdrom /mnt/cdrom
else
	mkdir /mnt/usb
	mount -t vfat /dev/sda1 /mnt/usb
fi

mkdir /mnt/newroot_ro

if [ "$MODE" = "cdrom" ]; then
	mount -t squashfs -o loop /mnt/cdrom/debianlive/root.sfs /mnt/newroot_ro
else
	mount -t squashfs -o loop /mnt/usb/debianlive/root.sfs /mnt/newroot_ro
fi

mkdir /mnt/newroot_rw
mount -t tmpfs -o size=16M tmpfs /mnt/newroot_rw

mkdir /mnt/newroot
mount -t overlayfs -o lowerdir=/mnt/newroot_ro,upperdir=/mnt/newroot_rw overlayfs /mnt/newroot

cd /mnt/newroot
mount --move . /
exec chroot . /sbin/init 3 </dev/console >/dev/console 2>&1

reboot -f
