#
# Copyright (C) 2005 Jimi Xenidis <jimix@watson.ibm.com>, IBM Corporation
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA
#
# $Id$
#


-include $(srcdir)/$(ISA)/$(CPU_GRP)/$(CPU_CORE)/Makefile.cpu

LTEXT=0x0

TARGETS +=

COMMON_OBJECTS += xh.o

EXTRA_TARGETS += \
	debug \
	decbounce \
	set_asr \
	set_dabr \
	tlbie


ifeq ($(USE_OPENFIRMWARE), yes)
libofd= ../lib/$(ISA)/$(CPU_GRP)/libofd.a
$(TARGETS): $(libofd)
INSTALL_IMGS += $(libofd)
HOST_LDLIBS += -lofd

TARGETS +=	oftest
INSTALL_IMGS += oftest
CONTROLLER_OBJECTS += $(top_builddir)/plugins/openfw/powerpc/32/of_image32.o
endif


CONTROLLER_OBJECTS += prom.o ofd_pci.o ofd_pci_ranges.o

HOST_PRE_CPPDIRS += -I.
